### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Per-Starke** [Hruschka/b-agile.de-site#17]

**Comment by gernotstarke** [comment]
I suggest to simplify the b-agile! logo to a fully rectangular shape, the current one is not legible.
Typical favicons don't waste whitespace, see the current google, youtube or github favicons.

@Hruschka - you could provide @Per-Starke with a few options or graphical ideas...

**Comment by gernotstarke** [comment]
(und ausnahmsweise werde ich DIESE Beratung nicht berechnen...)
